# Generated by Django 5.0.3 on 2024-03-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("two_f_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
