# Generated by Django 5.0.3 on 2024-03-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("two_f_auth", "0004_alter_user_sms_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=200),
        ),
    ]
