# Generated by Django 5.0.3 on 2024-03-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("two_f_auth", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(max_length=13, null=True),
        ),
    ]
