# Generated by Django 5.0.3 on 2024-03-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("two_f_auth", "0006_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sms_otp",
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
