# Generated by Django 5.0.3 on 2024-03-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("two_f_auth", "0007_alter_user_sms_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
